name = "Big Bungus Globe"
author = "Bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb5e3d45cd8a68ea482845651d7d127c496c3051d55efe5b062a342a1f468394"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
