name = "Big Bungus Globe"
author = "Bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b333a2e129d49211b04f0654f9878c4405af2689f298d22f0f8dacee2f4f595d"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
