name = "Big Bungus Globe"
author = "Bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c618ea1c397cde8518699e7e784ae0bf43bd5a3ab6f5897981a1f8baeb4241e4"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
