name = "Big Bungus Globe"
author = "Bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "202ee69c420e404bb0144e1550ba89d3523dfb1590ec1563fb0bf2ea8c0ebbed"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
