name = "Big Bungus Globe"
author = "Bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d266ffa310f84be129b757fd90b1c18344d873429edfe9edd8d8d4ccddbb169d"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
