name = "Big Bungus Globe"
author = "Bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a1acde5c0eaea2d2878c0d888013ce5e76dd3816453c38ae301551e9a7e7ab0"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
