name = "Big Bungus Globe"
author = "Bamsy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43a7e41dbe5c0761b0f47bb38b0b68f32244c5b27c744b3c6efa9a3e988679e1"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
